[build]
  command = "bundle exec jekyll build"
  publish = "_site"

[build.environment]
  RUBY_VERSION = "3.2.2"
  JEKYLL_ENV = "production"
  BUNDLE_WITHOUT = "test"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
  package = "@netlify/plugin-sitemap-ping"

  [plugins.inputs]
  sitemapPath = "/sitemap.xml"
