name: Ping Sitemap

on:
  push:
    branches:
      - main  # or "master" if that’s your default branch

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Google
        run: |
          curl "https://www.google.com/ping?sitemap=https://lakshyasinghchauhan.com/sitemap.xml"

      - name: Ping Bing
        run: |
          curl "https://www.bing.com/ping?sitemap=https://lakshyasinghchauhan.com/sitemap.xml"
